version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: node-auth-boilerplate
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
    depends_on:
      - db

volumes:
  db_data: